### ISSUE TITLE
where is app.Set?

### ISSUE THREAD

**Issue by zjw0358** [robinhood/faust#190]
i find app.Set in the docments ,

app.Set() – Define a new Set-based table
Use Set() to create a set table that only tracks membership and does not associate each key with a particular value:

users_with_transfer = app.Set('users-with-transfers', key_type=str)

@app.agent(transfers_topic)
async def transfer(transfers):
    async for transfer in transfers:
        users_with_transfer.add(transfer.username)

but when i run my code,

AttributeError: 'App' object has no attribute 'Set'

**Comment by ask** [comment]
There was a app.Set at one point, but it was not being used in any of our apps.
The feature was not tested well, and figured it was better to remove it than to ship with something that is potentially broken.

Instead of app.Set you could just use a table with True/False values to test for membership:

```
# add member to set
table[key] = True

# is member
key in table

# discard from set
table.pop(key, None)
```
