### ISSUE TITLE
Getting entry by key from windowed table returns all keys

### ISSUE THREAD

**Issue by fr-ser** [robinhood/faust#452]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.
I am using v 1.8.0 to avoid issue #450, but have checked to see the same behavior in the master branch

## Steps to reproduce

My goal is to expose a windowed table and return all windows for a key

## Expected behavior

By accessing the table with the correct key, I expect to only get values for that key

## Actual behavior

I get all values (regardless of the key) back.

## Full traceback

Repo to reproduce the issue:
https://github.com/fr-ser/faust-bugs/tree/master/window_key_bug

# Versions

* Python version: 3.7.3
* Faust version: 1.8.0
* Operating system: Ubuntu 19.04
* Kafka version: 2.12-2.3.0

**Comment by ask** [comment]
This is not really a bug, more like an accidental feature.

`table[k]` on a windowed table returns WindowSet instances, and this implements the MutableMapping interface.

What happens when you do `table[k].keys()` is that it will use the underlying table by default.

We *can* implement this in a number of ways:

1) filter out the keys we want
    this means the the operation will be O(n) where n is the number of keys in that partition space

2) maintain an index from k -> [windowedK]
     this will take up a lot of space, depending on the number of windows.

I'm not sure how often this feature will be used and 2) is very suboptimal if people don't use it.
1) could be a compromise, but I'm not a fan of hidden complexity like this: it looks like a simple operation you can use freely, but it can end up being very slow.

What is the use case here?
You could filter out the keys manually:

```py
def dump_windows_for_key(table, wanted_key):
    for windowed_key in table.keys():
        if windowed_key[0] == wanted_key:
            yield windowed_key

@app.timer(2.0)
async def print_table():
   print(f"up: {list(dump_windows_for_key(tumbling_table, 'counter_up')}")
    print(f"down: {list(dump_windows_for_key(tumbling_table, 'counter_down')}")
```

Another solution is 

3) Disallow using .keys() on a WindowSet raising NotImplementedError
     in such a way that people will be aware this is not doing what they expect it to.

**Comment by fr-ser** [comment]
I think raising a NotImplementedError makes the most sense here, as it is really unintuitive to access a WindowTable by key and getting all values back.

I think I could not use keys on the table directly as indexing it did not work for some reason, but I will make this into a separate bug if it is not fixed in the newest version
