### ISSUE TITLE
Using faust for anomaly detection

### ISSUE THREAD

**Issue by atahmasb** [robinhood/faust#522]
I am not sure where to post this question so I am creating an issue here hopefully someone could help.

I am building an anomaly detection service which looks at the past N (any integer) transactions of my app users (individually so the anomaly detection granularity is down to every single user) and detect any anomalies if a coming transaction value is higher than certain standard deviation of the past N transaction values. 

There are some considerations:

1) How can I use faust to keep track of this data for every single user? is faust good for this use case? Originally I was using Redis but that takes a longer time as every time I have to query the Redis db for the user and calculate the new statistics as well as the network time as my Redis is a hosted version.

2) if the first case is possible with faust, what happens if my faust app crashes and all the past users data is gone as faust keeps the data in a memory database. Especially some users might perform transactions over a long period of time. For example first transaction happens today and the next one 2 weeks later and so on. There is a chance that app crashes and all the data will be gone! 

Thank you

**Comment by StephenSorriaux** [comment]
We are successfully using Faust for a very similar use case, and:

1. Use a [Faust table](https://faust.readthedocs.io/en/latest/userguide/tables.html#tables) to store the information you need for every single user, make sure that you correctly partitioned your stream so that if you have multiple Faust workers it won't miss any messages (see [co-partitioning](https://faust.readthedocs.io/en/latest/userguide/tables.html#co-partitioning-tables-and-streams)). Also, make sure you are using a RocksDB backed table, else you will store it in memory which is not ideal in production mode.
2. By using a RocksDB backed table, data will actually be written on the worker filesystem. Moreover, when using a Faust table, your data are actually saved in a {table_name}-changelog topic in Kafka. You may loose data depending on how your topic is configured (by default its a compacted topic, with infinite retention -- so no risk).

**Comment by atahmasb** [comment]
Thanks for the help
